### ISSUE TITLE
Using the lib with PackageReference Include makes program uncompilable in VS2017 15.9.11

### ISSUE THREAD

**Issue by MagicAndre1981** [microsoft/vs-setup-samples#12]
As sson as I consume the lib via the new PackageReference Include, the solution fails to build:

```
   <PackageReference Include="Microsoft.VisualStudio.Setup.Configuration.Interop">
      <Version>1.16.30</Version>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
```

To repro the issue, checkout the repository, open the [Samples.sln](https://github.com/microsoft/vs-setup-samples/blob/master/Samples.sln) and compile it. The applications runs fine if packages.config is used. 

Now do a rightclick on `packages.config` and select migration to PackageReference and try to compile it again, but it fails:

![image](https://user-images.githubusercontent.com/8274816/57691496-a46d7000-7644-11e9-881b-1af72eafc942.png)

**Comment by MagicAndre1981** [comment]
I extracted the nuget package and see the following folder structure:

**microsoft.visualstudio.setup.configuration.interop.1.16.30\lib\net35**

so it only includes a .net 3.5 DLL, but I use a .net 4.x program. Is this the cause? Can a .net 4.52 version be added?

**Comment by heaths** [comment]
The nuget package is not currently compatible with SDK-style .csproj project files. We have an internal bug tracking this but has not been a priority. The same DLL will work, though you can't embed the interop types until, IIRC, .NET Core 2.1. A couple of attributes in the PIA are not part of .NET Core until 2.1 (definitely in 3.0 preview).

**Comment by MagicAndre1981** [comment]
ok, so I have to use old packages.config? This requires me to remove and install all packages again in old packages.config style. Hopefully this works.

**Comment by MagicAndre1981** [comment]
ok, works and I can get VS2017 install path

**Comment by MagicAndre1981** [comment]
it looks like it works with [2.3.2200-develop-g2d3a6646](https://www.nuget.org/packages/Microsoft.VisualStudio.Setup.Configuration.Interop/2.3.2200-develop-g2d3a6646). 

@heaths 

When is final expected? When VS2019 16.3 and .net core 3.0 ship as GA?

**Comment by heaths** [comment]
These packages are on a different ship cycle so we could publish a release package any time. The functional bits - at least for this change - are final, though.

**Comment by MagicAndre1981** [comment]
@heaths

so, we can use this version now? Go-Live?

**Comment by heaths** [comment]
Yes.

**Comment by heaths** [comment]
Release version 2.3.2262 for both the native and PIA packages are now available.

**Comment by MagicAndre1981** [comment]
> Release version 2.3.2262 for both the native and PIA packages are now available.

still listed as prerelease version. so still no final?

**Comment by heaths** [comment]
2.3.2262 is a release version in semver. If you're referring to the "RC" in the icon, that's an irrelevant bug we'll have to fix in a future release.

**Comment by MagicAndre1981** [comment]
> 2.3.2262 is a release version in semver. If you're referring to the "RC" in the icon, that's an irrelevant bug we'll have to fix in a future release.

On the [nuget page for 2.3.2262-g94fae01e](https://www.nuget.org/packages/Microsoft.VisualStudio.Setup.Configuration.Interop/2.3.2262-g94fae01e) it is written that it is pre-release so I guess I have to enable checkox "include prerelease" in nuget Ui to get it shown.

![image](https://user-images.githubusercontent.com/8274816/63999833-b21c0800-cb04-11e9-8477-23b3e2365fd1.png)

I'll check this on monday in office

**Comment by heaths** [comment]
You're right, I was accidentally looking at the native package. I'll open a bug against our internal sources but I have no idea when it will be fixed.

**Comment by MagicAndre1981** [comment]
ok, I made the update to last version after enabling checkbox "include prerelease" in nuget UI to get the update offered.
