### ISSUE TITLE
Not Detecting Visual Studio 2008 (Version 9)

### ISSUE THREAD

**Issue by kjkazinski** [microsoft/vs-setup-samples#13]
I ran vswhere and it is not returning any information for VS2008.

I a couple of combinations "vswhere -legacy", "vswhere -all" and even "vswhere -legacy -all".

I get results for VS 10 *installationVersion: 10.0) but not 9.

Am I missing something?

**Comment by heaths** [comment]
Feedback for vswhere should go to https://github.com/microsoft/vswhere; however, it only detects back to VS2010. VS2008 is out of support.
