### ISSUE TITLE
Cannot determine MSVC on Windows ARM64

### ISSUE THREAD

**Issue by Alovchin91** [microsoft/vs-setup-samples#15]
Hi,

The SetupConfiguration COM component currently cannot be used to determine MSVC installation on Windows ARM64.

This prevents tools like **rustc** from finding link.exe and C++ stdlib: https://github.com/rust-lang/rust/issues/83043

The issue has been reported on Developer Community twice but both cases are as of now ignored:

https://developercommunity.visualstudio.com/t/setupconfiguration-doesnt-find-any-vs-installation/1232316
https://developercommunity.visualstudio.com/t/isetupconfiguration-is-not-registered-on-arm64/1236604

One of the easiest solutions would be to register an out-of-process DLL surrogate on ARM64: https://docs.microsoft.com/en-us/windows/win32/com/using-the-system-supplied-surrogate

This shouldn't be too hard to do so I hope somebody could do that in their Crafting days :)

Thanks!

**Comment by heaths** [comment]
The COM APIs and tools built on them like https://github.com/microsoft/vswhere are not designed nor contain enough information to find files within individual components. See the aforementioned link for samples, though, of how you can find various tools including a [sample](https://github.com/microsoft/vswhere/wiki/Find-VC) to find VC toolsets.

**Comment by Alovchin91** [comment]
@heaths  Thank you for the response. This is not the exact issue; the same logic works perfectly in x86 and x64 processes. The issue is that the COM component cannot be accessed as-is from an arm64 process because it's supposed to run in-proc and it's only registered for x86 and x64.

I don't really know how to phrase the issue so that somebody at Microsoft finally gave it some proper attention 😞

**Comment by heaths** [comment]
I've forwarded on the request to the proper team.

**Comment by Alovchin91** [comment]
Thanks!
