### ISSUE TITLE
Obtaining the full path to cl.exe

### ISSUE THREAD

**Issue by T-640** [microsoft/vs-setup-samples#16]
Hello!

Is there a function that obtains the full path to cl.exe, or at least gives the closest path to it? The best equivalent I could find is the GetInstallationPath function, but it gets me only as far as C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools

I can certainly work with that, but I would rather prefer the library locating the cl.exe for me.

**Comment by heaths** [comment]
We do not store and cannot retrieve paths to individual files. Please see https://github.com/microsoft/vswhere/wiki for examples.

**Comment by T-640** [comment]
As far as I understand vswhere is a standalone executable only. What I need is a library that I can link to my own executable (the reason I used sample from here in the first place). Fine if it does not get me path to an individual file, I was hoping that at least there would be a way to automatically obtain path further down the BuildTools directory with any of API from Setup.Configuration.h.

**Comment by heaths** [comment]
vswhere is just a client of the same APIs. With the root directory, the wiki can show you how to find cl.exe.
