### ISSUE TITLE
Unable to build C++ sample.

### ISSUE THREAD

**Issue by profiler-bg** [Microsoft/vs-setup-samples#2]
Hi, 

Tried building the sample in both VS2015 & VS2017RC with no success in both.

VS2017RC: Due to new NuGet doesn't even offer to restore packages.
VS2015: Complains that the project references a package with version: 1.2.194-develop-24916 which it is unable to find in the NuGet repo. I'm unable to update or remove it (so I can install the 1.3 version).

Is this expected behaviour?

Regards,
HP

**Comment by profiler-bg** [comment]
The solution I used was:
1. Delete packages.config.
2. Open Setup.Configuration.VC.vcxproj with VS code and delete the condition on line 185 that checks if the specific version is installed.
3. Open solution in VS2015.
4. Manually install the latest Microsoft.VisualStudio.Setup.Configuration.Native package.

**Comment by heaths** [comment]
Seems I never published version 1.2.194, but updating to 1.2.304 via the NuGet interface should've worked. I'll be fixing this but updating to our RC bits anyway.
