### ISSUE TITLE
Minimal Build tools setup doesn't register COM

### ISSUE THREAD

**Issue by refack** [Microsoft/vs-setup-samples#5]
I installed the "Build Tools for Visual Studio 2017 RC" on windows 7 pro SP1, in a very minimal way (i.e. I uncheck some of the components) and the COM wasn't registered... I'll try to repro.

**Comment by refack** [comment]
@heaths I have a reproducing VM. You want a copy?

**Comment by heaths** [comment]
The bug should be fixed by RTW.

**Comment by heaths** [comment]
Confirmed fixed for RTW.
