### ISSUE TITLE
Find installed extensions

### ISSUE THREAD

**Issue by twsouthwick** [Microsoft/vs-setup-samples#9]
Is it possible to use these APIs to get installed extensions? In the experimental instance? I'm developing an extension and have a couple instances of VS installed and need to determine which one has the deployed extension during development.

**Comment by heaths** [comment]
`ISetupPackageReference::GetIsExtension` can help, but it only works for per-machine extensions. Per-user extensions are still handled solely through the Extension Manager APIs. Traditional VS APIs (within a running VS) should continue to work for both.
